<?php


/**
 * Base class that represents a query for the 'municipio' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Sun Feb 10 15:53:08 2013
 *
 * @method     MunicipioQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     MunicipioQuery orderByMunicipio($order = Criteria::ASC) Order by the municipio column
 * @method     MunicipioQuery orderByEstado($order = Criteria::ASC) Order by the estado column
 *
 * @method     MunicipioQuery groupById() Group by the id column
 * @method     MunicipioQuery groupByMunicipio() Group by the municipio column
 * @method     MunicipioQuery groupByEstado() Group by the estado column
 *
 * @method     MunicipioQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     MunicipioQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     MunicipioQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     Municipio findOne(PropelPDO $con = null) Return the first Municipio matching the query
 * @method     Municipio findOneOrCreate(PropelPDO $con = null) Return the first Municipio matching the query, or a new Municipio object populated from the query conditions when no match is found
 *
 * @method     Municipio findOneById(int $id) Return the first Municipio filtered by the id column
 * @method     Municipio findOneByMunicipio(string $municipio) Return the first Municipio filtered by the municipio column
 * @method     Municipio findOneByEstado(string $estado) Return the first Municipio filtered by the estado column
 *
 * @method     array findById(int $id) Return Municipio objects filtered by the id column
 * @method     array findByMunicipio(string $municipio) Return Municipio objects filtered by the municipio column
 * @method     array findByEstado(string $estado) Return Municipio objects filtered by the estado column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseMunicipioQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseMunicipioQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Municipio', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new MunicipioQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    MunicipioQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof MunicipioQuery) {
			return $criteria;
		}
		$query = new MunicipioQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Municipio|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = MunicipioPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    MunicipioQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(MunicipioPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    MunicipioQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(MunicipioPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MunicipioQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(MunicipioPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the municipio column
	 * 
	 * @param     string $municipio The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MunicipioQuery The current query, for fluid interface
	 */
	public function filterByMunicipio($municipio = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($municipio)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $municipio)) {
				$municipio = str_replace('*', '%', $municipio);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MunicipioPeer::MUNICIPIO, $municipio, $comparison);
	}

	/**
	 * Filter the query on the estado column
	 * 
	 * @param     string $estado The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MunicipioQuery The current query, for fluid interface
	 */
	public function filterByEstado($estado = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($estado)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $estado)) {
				$estado = str_replace('*', '%', $estado);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MunicipioPeer::ESTADO, $estado, $comparison);
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Municipio $municipio Object to remove from the list of results
	 *
	 * @return    MunicipioQuery The current query, for fluid interface
	 */
	public function prune($municipio = null)
	{
		if ($municipio) {
			$this->addUsingAlias(MunicipioPeer::ID, $municipio->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseMunicipioQuery
