<?php


/**
 * Base class that represents a query for the 'estado' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Sat Mar  9 12:50:36 2013
 *
 * @method     EstadoQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     EstadoQuery orderByNombre($order = Criteria::ASC) Order by the nombre column
 *
 * @method     EstadoQuery groupById() Group by the id column
 * @method     EstadoQuery groupByNombre() Group by the nombre column
 *
 * @method     EstadoQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     EstadoQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     EstadoQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     Estado findOne(PropelPDO $con = null) Return the first Estado matching the query
 * @method     Estado findOneOrCreate(PropelPDO $con = null) Return the first Estado matching the query, or a new Estado object populated from the query conditions when no match is found
 *
 * @method     Estado findOneById(int $id) Return the first Estado filtered by the id column
 * @method     Estado findOneByNombre(string $nombre) Return the first Estado filtered by the nombre column
 *
 * @method     array findById(int $id) Return Estado objects filtered by the id column
 * @method     array findByNombre(string $nombre) Return Estado objects filtered by the nombre column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseEstadoQuery extends ModelCriteria
{

	/**
	 * Initializes internal state of BaseEstadoQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Estado', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new EstadoQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    EstadoQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof EstadoQuery) {
			return $criteria;
		}
		$query = new EstadoQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key
	 * Use instance pooling to avoid a database query if the object exists
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Estado|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ((null !== ($obj = EstadoPeer::getInstanceFromPool((string) $key))) && $this->getFormatter()->isObjectFormatter()) {
			// the object is alredy in the instance pool
			return $obj;
		} else {
			// the object has not been requested yet, or the formatter is not an object formatter
			$criteria = $this->isKeepQuery() ? clone $this : $this;
			$stmt = $criteria
				->filterByPrimaryKey($key)
				->getSelectStatement($con);
			return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
		}
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{	
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		return $this
			->filterByPrimaryKeys($keys)
			->find($con);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    EstadoQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(EstadoPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    EstadoQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(EstadoPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 * 
	 * @param     int|array $id The value to use as filter.
	 *            Accepts an associative array('min' => $minValue, 'max' => $maxValue)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    EstadoQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(EstadoPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the nombre column
	 * 
	 * @param     string $nombre The value to use as filter.
	 *            Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    EstadoQuery The current query, for fluid interface
	 */
	public function filterByNombre($nombre = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($nombre)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $nombre)) {
				$nombre = str_replace('*', '%', $nombre);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(EstadoPeer::NOMBRE, $nombre, $comparison);
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Estado $estado Object to remove from the list of results
	 *
	 * @return    EstadoQuery The current query, for fluid interface
	 */
	public function prune($estado = null)
	{
		if ($estado) {
			$this->addUsingAlias(EstadoPeer::ID, $estado->getId(), Criteria::NOT_EQUAL);
	  }
	  
		return $this;
	}

} // BaseEstadoQuery
