<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/06 20:41:43
sfConfig::add(array(
  'mod_sfguarduserprofile_enabled' => true,
  'mod_sfguarduserprofile_view_class' => 'sfPHP',
));
