<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/06 20:41:52
sfConfig::add(array(
  'mod_respuesta_encuesta_visitante_enabled' => true,
  'mod_respuesta_encuesta_visitante_view_class' => 'sfPHP',
));
