<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/06/06 16:01:43
sfConfig::add(array(
  'mod_respuesta_encuesta_enabled' => true,
  'mod_respuesta_encuesta_view_class' => 'sfPHP',
));
