<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/03 10:02:24

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'pgsql:host=localhost;dbname=filven',
  'username' => 'filven',
  'password' => 'nirvana',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
