<?php



/**
 * Skeleton subclass for performing query and update operations on the 'actividad' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Sat Jan 26 19:26:54 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ActividadQuery extends BaseActividadQuery {

    static public function proximasactividadessala($id_sala, $fecha){
        
        $Actividades = ActividadQuery::create()
                          ->condition('cond1', 'Actividad.FechaHora >= ?', $fecha)
                          ->condition('cond2', 'Actividad.IdSala = ?', $id_sala)
                          ->where(array('cond1', 'cond2'), 'and')
                          ->orderByFechaHora('asc')
                          ->find();   
        
        return $Actividades;
    }
} // ActividadQuery
