<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_user_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Sat Jan 26 21:59:41 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class sfGuardUserProfileQuery extends BasesfGuardUserProfileQuery {

} // sfGuardUserProfileQuery
