propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  actividad:
    _attributes: { phpName: Actividad }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre_actividad: { phpName: NombreActividad, type: VARCHAR, size: '255', required: false }
    ponente: { phpName: Ponente, type: VARCHAR, size: '255', required: false }
    turno: { phpName: Turno, type: BOOLEAN, required: false }
    ejecutada: { phpName: Ejecutada, type: BOOLEAN, required: false }
    cantidad_participantes_m: { phpName: CantidadParticipantesM, type: INTEGER, required: false }
    cantidad_participantes_f: { phpName: CantidadParticipantesF, type: INTEGER, required: false }
    alcanzo_tiempo: { phpName: AlcanzoTiempo, type: BOOLEAN, required: false }
    causas_incumplimiento: { phpName: CausasIncumplimiento, type: VARCHAR, size: '255', required: false }
    id_municipio: { phpName: IdMunicipio, type: INTEGER, required: false }
    escuela: { phpName: Escuela, type: BOOLEAN, required: false }
    refugio: { phpName: Refugio, type: BOOLEAN, required: false }
    observaciones: { phpName: Observaciones, type: VARCHAR, size: '255', required: false }
    id_sala: { phpName: IdSala, type: INTEGER, required: false, foreignTable: sala, foreignReference: id, onUpdate: CASCADE }
    id_tipo_actividad: { phpName: IdTipoActividad, type: INTEGER, required: false, foreignTable: tipo_actividad, foreignReference: id, onUpdate: CASCADE }
    fecha_hora: { phpName: FechaHora, type: TIMESTAMP, required: false }
  encuesta:
    _attributes: { phpName: Encuesta }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre_encuesta: { phpName: NombreEncuesta, type: VARCHAR, size: '255', required: false }
    descripcion_encuesta: { phpName: DescripcionEncuesta, type: VARCHAR, size: '255', required: false }
    tipo_encuesta: { phpName: TipoEncuesta, type: VARCHAR, size: '255', required: false }
    fecha_elaboracion: { phpName: FechaElaboracion, type: DATE, required: false, defaultExpr: now() }
  informe:
    _attributes: { phpName: Informe }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    titulo_informe: { phpName: TituloInforme, type: VARCHAR, size: '255', required: false }
    fecha_informe: { phpName: FechaInforme, type: TIMESTAMP, required: false }
    creado_por: { phpName: CreadoPor, type: VARCHAR, size: '255', required: false }
  item:
    _attributes: { phpName: Item }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    texto: { phpName: Texto, type: VARCHAR, size: '255', required: false }
    id_encuesta: { phpName: IdEncuesta, type: INTEGER, required: false, foreignTable: encuesta, foreignReference: id, onUpdate: CASCADE }
    seleccion_simple: { phpName: SeleccionSimple, type: BOOLEAN, required: false, defaultValue: true }
    identificador_item: { phpName: IdentificadorItem, type: INTEGER, required: false }
  municipio:
    _attributes: { phpName: Municipio }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    municipio: { phpName: Municipio, type: VARCHAR, size: '255', required: false }
    estado: { phpName: Estado, type: VARCHAR, size: '255', required: false }
  opcion_respuesta:
    _attributes: { phpName: OpcionRespuesta }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    id_item: { phpName: IdItem, type: INTEGER, required: false, foreignTable: item, foreignReference: id, onUpdate: CASCADE }
    respuesta: { phpName: Respuesta, type: VARCHAR, size: '255', required: false }
    seleccion_simple: { phpName: SeleccionSimple, type: BOOLEAN, required: false, defaultValue: true }
  pagina:
    _attributes: { phpName: Pagina }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    id_informe: { phpName: IdInforme, type: INTEGER, required: false, foreignTable: informe, foreignReference: id, onUpdate: CASCADE }
    titulo_informe: { phpName: TituloInforme, type: VARCHAR, size: '255', required: false }
    ante_cuadro: { phpName: AnteCuadro, type: VARCHAR, size: '255', required: false }
    titulo_cuadro: { phpName: TituloCuadro, type: VARCHAR, size: '255', required: false }
    post_cuadro: { phpName: PostCuadro, type: VARCHAR, size: '255', required: false }
    texto_posterior: { phpName: TextoPosterior, type: VARCHAR, size: '255', required: false }
    ante_grafico: { phpName: AnteGrafico, type: VARCHAR, size: '255', required: false }
    post_grafico: { phpName: PostGrafico, type: VARCHAR, size: '255', required: false }
    tipo_grafico: { phpName: TipoGrafico, type: INTEGER, required: false }
  respuesta_encuesta:
    _attributes: { phpName: RespuestaEncuesta }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    id_item: { phpName: IdItem, type: INTEGER, required: false, foreignTable: item, foreignReference: id, onUpdate: CASCADE }
    respuesta: { phpName: Respuesta, type: VARCHAR, size: '255', required: false }
  sala:
    _attributes: { phpName: Sala }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre_sala: { phpName: NombreSala, type: VARCHAR, size: '255', required: false }
    descripcion_sala: { phpName: DescripcionSala, type: VARCHAR, size: '255', required: false }

  sf_guard_user_profile:
    _attributes: { phpName: SfGuardUserProfile }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    user_id: { phpName: UserId, type: INTEGER, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: CASCADE }
    first_name: { phpName: FirstName, type: VARCHAR, size: '20', required: false }
    last_name: { phpName: LastName, type: VARCHAR, size: '20', required: false }
    birthday: { phpName: Birthday, type: DATE, required: false }
  tipo_actividad:
    _attributes: { phpName: TipoActividad }
    id: { phpName: Id, type: INTEGER, primaryKey: true, autoIncrement: true, required: true }
    nombre_tipo: { phpName: NombreTipo, type: VARCHAR, size: '255', required: false }
    descripcion_tipo: { phpName: DescripcionTipo, type: VARCHAR, size: '255', required: false }
  visitante:
    _attributes: { phpName: Visitante }
    id: { phpName: Id, type: BIGINT, primaryKey: true, autoIncrement: true, required: true }
    fecha: { phpName: Fecha, type: DATE, required: false }
    numero: { phpName: Numero, type: INTEGER, required: false }
