<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/03 01:15:26
sfConfig::add(array(
  'mod_tipo_actividad_enabled' => true,
  'mod_tipo_actividad_view_class' => 'sfPHP',
));
