<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/09 17:48:18
sfConfig::add(array(
  'mod_sfguarduserprofile_enabled' => true,
  'mod_sfguarduserprofile_view_class' => 'sfPHP',
));
