<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/09 18:48:14
sfConfig::add(array(
  'mod_tipo_actividad_enabled' => true,
  'mod_tipo_actividad_view_class' => 'sfPHP',
));
