<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/03 01:27:33
sfConfig::add(array(
  'mod_respuesta_encuesta_visitante_enabled' => true,
  'mod_respuesta_encuesta_visitante_view_class' => 'sfPHP',
));
