<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/10 11:24:59

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'pgsql:host=localhost;dbname=filven',
  'username' => 'postgres',
  'password' => 'postgres',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
